Update packfile.c
DCurrent/openbor pull request #212
Opened 2020-12-06 11:02 UTC by msmalik681

This seems to fix any issues compiling android or windows ports don't know if changing the file open mode will have any negative impact but on a test everything seems fine no file corruption games load and run as they should from both pak file or data folder.

2020-12-06 14:08 UTC, DCurrent requested changes
@msmalik681 I'm not really OK with setting full permissions to files like that. It's almost begging for a security exploit. If there's no other way I'll approve it, but please experiment with a more limit set of permissions first.

2020-12-06 20:28 UTC, msmalik681 commented
@DCurrent what is we remove the permission flag is that the same as 0 ? can you suggest any work around as the android compiler will not play nice unless with the current read settings.

2020-12-06 20:59 UTC, msmalik681 commented
I have tried many different configurations for opening files this is the only way it will work as needed can we use this until a better method is discovered.

2020-12-06 22:00 UTC, DCurrent commented
Which combinations did you try? I can't believe at minimum 500 permissions won't work. There's simply no way Android is going to require read, write, and execute on all permission groups to run an app. I'm sorry, but I just can't allow that in good conscience until it is very thoroughly investigated. This is the kind of thing that makes a device wide open for malicious actors to brick it, or worse. Had I noticed before I wouldn't have allowed the change when it was first applied.

2020-12-06 23:04 UTC, DCurrent commented
@msmalik681 I assume you are familiar with file permission setup, but just in case, have a look here to see what I mean: https://www.maketecheasier.com/file-permissions-what-does-chmod-777-means/

2020-12-07 12:55 UTC, msmalik681 commented
@DCurrent found a silly fix for a silly issue seems the new android NDK has tighter restrictions on file access I did not really change anything beside making file access read and write instead of read write and execute test on a game managed to get through a level and it saved just fine all the configurations saved fine and there was no file corruption.

2020-12-07 13:26 UTC, merged